# Generated by Django 5.0.2 on 2024-02-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneName', models.CharField(db_index=True, max_length=250)),
                ('phoneMarka', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('costType', models.CharField(max_length=10)),
                ('phoneMemory', models.PositiveSmallIntegerField()),
                ('phoneColor', models.CharField(max_length=20)),
                ('document', models.BooleanField(default=False)),
                ('isNew', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('adress', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
