# Generated by Django 5.0.2 on 2024-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'created'), ('2', 'confirmed'), ('3', 'rejected')], default='1', max_length=30),
        ),
    ]
