# Generated by Django 5.0.2 on 2024-03-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='user',
        ),
    ]
