# Generated by Django 5.0.2 on 2024-03-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0004_alter_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='ProductsApp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
