# Generated by Django 5.0.2 on 2024-03-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0004_remove_product_views_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ProductsApp.product'),
        ),
    ]
